# -*- coding: utf-8 -*-
"""Road_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yO21exBIZOVUz4hIZS25QM7aLrbeX0i1
"""

!pip install osmnx

import osmnx as ox

# 設定地點
place_name = "Jamaica Beach, Texas, USA"

G = ox.graph_from_place(place_name, network_type="all")
ox.plot_graph(G, bgcolor="white", node_size=10, edge_linewidth=0.5)

import geopandas as gpd

buildings = ox.features_from_place(place_name, tags={"building": True})
buildings.plot(figsize=(10, 10), color="gray", edgecolor="black")

buildings_gdf = buildings[["geometry"]]
print(buildings_gdf.head())

!pip install osmnx

import osmnx as ox
import matplotlib.pyplot as plt

place_name = "Jamaica Beach, Texas, USA"

G = ox.graph_from_place(place_name, network_type='drive')

tags = {'building': True}
buildings = ox.features_from_place(place_name, tags={"building": True})


fig, ax = ox.plot_graph(G, figsize=(10, 10), show=False, close=False)

if not buildings.empty:
    buildings.plot(ax=ax, facecolor='red', alpha=0.5)
plt.show()

!pip install osmnx

import osmnx as ox
import matplotlib.pyplot as plt

place_name = "Jamaica Beach, Texas, USA"

# 获取该区域的道路网络（network_type 可根据需要设置，如 'drive'、'walk' 等）
G = ox.graph_from_place(place_name, network_type='drive')


buildings = ox.features_from_place(place_name, tags={"building": True})


fig, ax = ox.plot_graph(G, figsize=(10, 10), show=False, close=False,
                          bgcolor='white', edge_color='blue')

if not buildings.empty:
    buildings.plot(ax=ax, facecolor='red', alpha=0.5)

plt.show()

# 在 Colab 上首先安装 osmnx
!pip install osmnx

import osmnx as ox
import matplotlib.pyplot as plt

# 定义查询区域
place_name = "Jamaica Beach, Texas, USA"

# 获取该区域的道路网络（例如：驾车道路）
G = ox.graph_from_place(place_name, network_type='drive')

# 获取建筑物数据
buildings = ox.features_from_place(place_name, tags={"building": True})

# 获取电力杆数据
electric_poles = ox.features_from_place(place_name, tags={"power": "pole"})

# 获取电网线路数据
power_lines = ox.features_from_place(place_name, tags={"power": "line"})

# 绘制道路网络：白色背景，蓝色道路
fig, ax = ox.plot_graph(G, figsize=(10, 10), show=False, close=False,
                          bgcolor='white', edge_color='blue')

# 绘制建筑物（红色半透明）
if not buildings.empty:
    buildings.plot(ax=ax, facecolor='red', alpha=0.5)

# 绘制电力杆（黄色圆点）
if not electric_poles.empty:
    electric_poles.plot(ax=ax, marker='o', color='yellow', markersize=5)

# 绘制电网线路（绿色线条）
if not power_lines.empty:
    power_lines.plot(ax=ax, color='green')

plt.show()